apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration-equal
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
    - effect: NoExecute
      key: app
      operator: Equal
      value: dev

status: {}
