apiVersion: v1
kind: Pod
metadata:
  name: nginx-prefer
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100 # weight에 따라서 조건이 충족될때 어떤 노드에 배치될지 우선순위설정
          preference:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - dev
        - weight: 10
          preference:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - prod
status: {}
