apiVersion: v1
kind: Pod
metadata:
  name: nginx-required
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  # tolerations:
  #   - effect: NoSchedule
  #     key: app
  #     operator: Exists
  # value: test
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: app
                operator: In
                values:
                  - dev
status: {}
