apiVersion: v1
data:
  PGDATA: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL3BnZGF0YQ==
  POSTGRES_DB: YWRtaW4=
  POSTGRES_PASSWORD: MTIzNA==
  POSTGRES_USER: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-secrets
