apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-svc
  name: postgres-svc
spec:
  ports:
    - name: 5432-5432
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
