apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: sharedvolume
        mountPath: /usr/share/nginx/html
    resources: {}

  - image: registry.k8s.io/git-sync/git-sync:v3.6.6
    name: git-sync
    args: ["--repo=https://github.com/jigeria/k8s", "--root=/tmp/vol/", "--branch=main", "--dest=sync-data"]
    volumeMounts:
      - name: tmpvolume
        mountPath: /tmp/vol

  - image: busybox
    name: sidecar-container
    command: ["/bin/sh"]
    args: ["-c", "while true; do cp /tmp/tmpvolume/sync-data/*.html /tmp/sharedvolume ; sleep 5; done"]
    volumeMounts:
      - name: sharedvolume
        mountPath: /tmp/sharedvolume
      - name: tmpvolume
        mountPath: /tmp/tmpvolume
    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: sharedvolume
      emptyDir: {}
    - name: tmpvolume
      emptyDir: {}
status: {}
