apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: sharedvolume
        mountPath: /usr/share/nginx/html
    resources: {}
  - image: busybox
    name: sidecar-container
    command: ["/bin/sh"]
    args: ["-c", "while true; do wget -O /tmp/vol/index.html https://gist.github.com/jigeria/a598392c0517696405c48e42b4b15fbe/raw/index.html; sleep 5; done"]
    volumeMounts:
      - name: sharedvolume
        mountPath: /tmp/vol
    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: sharedvolume
      emptyDir: {}
status: {}
