apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  containers:
    - image: redis
      name: redis
      volumeMounts:
        - mountPath: /data
          name: redis
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  # nodeName: node2
  volumes:
    - name: redis
      persistentVolumeClaim:
        claimName: redis
status: {}
