all:
  hosts:
    vm1:
      ansible_host: 192.168.64.189
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ansible
    vm2:
      ansible_host: 192.168.64.190
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ansible
    vm3:
      ansible_host: 192.168.64.191
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ansible
    vm4:
      ansible_host: 192.168.64.192
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ansible
  children:
    master:
      hosts:
        vm1:
    control-planes:
      hosts:
        vm1:
    nodes:
      hosts:
        vm2:
        vm3:
        vm4:
