apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    # - name: secret2-volume
    #   mountPath: "/etc/foo"
    #   readOnly: true
    - name: secret1-volume
      mountPath: "/etc/bar"
      readOnly: true
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret1
          key: username
          optional: false
  volumes:
  # - name: secret2-volume
  #   secret:
  #     secretName: secret2
  #     optional: false
  - name: secret1-volume
    secret:
      secretName: secret1
      optional: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
