apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: NAME
      valueFrom:
        configMapKeyRef:
            name: test
            key: name
  #   volumeMounts:
  #   - name: config
  #     mountPath: "/tmp/config"
  #     readOnly: true
  # volumes:
  # - name: config
  #   configMap:
  #     name: company
